version: 2
jobs:
  build:
    docker:
      - image: ubuntu:19.04
    steps:
      - checkout
      - run:
          name: Install
          command: apt update && apt install -y build-essential clang-format bc
      - run:
          name: Test
          command: make test
